CREATE TABLE `user` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `USER_NAME` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '活动编码',
  `NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '活动名称',
  `AGE` bigint DEFAULT NULL COMMENT '年龄',
  `BALANCE` decimal(10,2) COMMENT '金额',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `UNIQ_LUCKYDRAW_CODE` (`TENANT_CODE`,`CODE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=524 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户表';

insert into `user` (ID,USER_NAME,NAME,AGE,BALANCE) VALUES(1,'account1','张三',20,100.00);
insert into `user` (ID,USER_NAME,NAME,AGE,BALANCE) VALUES(2,'account2','李四',28,180.00);
